---
# tasks file for Google_Drive
- name: Google Drive | Genera access token
  include_tasks: generar_token.yml

- name: Google Drive | Descargar archivos
  include_tasks: descargar.yml
  when: descargar | bool

- name: Google Drive | Subir archivos
  include_tasks: subir.yml
  when: subir | bool

- name: Google Drive | Eliminar archivos o carpeta
  include_tasks: eliminar.yml
  when: eliminar | bool
...
