---
- name: Google Drive | Subida | Valida si la ruta local existe
  stat:
    path: "{{ ruta }}"
  register: validacion

- name: Google Drive | Subida | Error controlado en caso de que la ruta ingresa no exista.
  fail:
    msg: "[x] La ruta {{ ruta }} no existe en el equipo local, por favor verificar."
  when: not validacion.stat.exists

- name: Google Drive | Subida | Subir archivos en un directorio
  include_tasks: subir_directorio.yml
  when: es_directorio | bool

- name: Google Drive | Subida | Subir archivos o lista de archivos
  include_tasks: subir_archivos.yml
  when: es_archivo | bool 
...
