---
- name: Google Drive | Subida | Encuentra todos los archivos en un directorio en especifico
  find:
    paths: "{{ ruta }}"
    file_type: file
    recurse: false
  register: archivos
  no_log: true

- set_fact:
    lista_archivos: "{{ lista_archivos | default([]) + item | map(attribute='path') }}"
  changed_when: true
  notify: "Google Drive | Subida | Sube los archivos"
  no_log: true
  loop:
    - "{{ archivos.files }}"

- meta: flush_handlers

- name: Google Drive | Subida | Mensaje SI la subida fue exitosa
  debug:
    msg: "Archivos subidos exitosamente: {{ archivos_subidos | join(', ') }}"
  when: archivos_subidos | length > 0
  vars:
    archivos_subidos: "{{ subida.results | selectattr('status', 'equalto', 200) | map(attribute='json.name') | list }}"
...
